export const KAZAKHSTAN_CITIES = [
  "Abai",
  "Aktau",
  "Aktobe",
  "Almaty",
  "Arkalyk",
  "Astana",
  "Atyrau",
  "Balkhash",
  "Ekibastuz",
  "Jezkazgan",
  "Karaganda",
  "Kaskelen",
  "Kentau",
  "Kokshetau",
  "Konaev",
  "Kostanay",
  "Kulsary",
  "Kyzylorda",
  "Oral",
  "Oskemen",
  "Pavlodar",
  "Petropavl",
  "Ridder",
  "Rudny",
  "Saran",
  "Sarkand",
  "Semey",
  "Shymkent",
  "Stepnogorsk",
  "Taldykorgan",
  "Taraz",
  "Temirtau",
  "Turkistan",
  "Zhanaozen",
] as const;

export type KazakhstanCity = (typeof KAZAKHSTAN_CITIES)[number];
